### ISSUE TITLE
Error when used with individual handler in micro-api

### ISSUE THREAD

**Issue by vinaypuppal** [possibilities/micro-cors#13]
`const api = cors(microApi([ ...` is  working, but if i try on individual handler i am getting an error

`TypeError: Cannot read property 'setHeader' of undefined`

Sample repo https://github.com/vinaypuppal/micro-cors-error

**Comment by possibilities** [comment]
Yeah, I guess this isn't going to work because `micro-api`'s handlers have their own "api" that's different than `micro` itself.

**Comment by possibilities** [comment]
I think it might just be an unavoidable disadvantage of `micro-api`‘s approach. If you have any thoughts how I can make everything work together more nicely let me know.

**Comment by vinaypuppal** [comment]
oh okay thanks for looking into it, for my use case `const api = cors(microApi([ ...` is sufficient. Just reported as it's not working on the handler.

**Comment by possibilities** [comment]
Thanks!
