### ISSUE TITLE
Error with microrouter

### ISSUE THREAD

**Issue by obiwarn** [possibilities/micro-cors#26]
My code:

```
import micro from 'micro'
import auth from './auth'
import routes from './routes'
import cors from 'micro-cors'

micro(cors(auth(routes))).listen(3000)
```

then I get

```
TypeError: "string" must be a string, Buffer, or ArrayBuffer
    at Function.byteLength (buffer.js:441:11)
```

**Comment by possibilities** [comment]
I _think_ (without investigating directly) that it's just a negative side effect of the way this library works. If I'm missing it and there's a nice way around this please let me know. Thanks!

**Comment by possibilities** [comment]
That is _this_ library... meaning micro-cors... does not compose nicely the way we imagine it should.

**Comment by joseph1125** [comment]
use `const cors = require('micro-cors')()`

It is important to include `()`

**Comment by jeroenptrs** [comment]
@joseph1125 no, that error happens even with `()` added after the import

**Comment by joseph1125** [comment]
@jeroenptrs That's why I suggest to use require before they fix this issue

**Comment by jeroenptrs** [comment]
@joseph1125 also at require. It just fails, period.

**Comment by possibilities** [comment]
I'm completely detached from this project if anyone wants to pick it up? (:

**Comment by amio** [comment]
@obiwarn Could you provide a minimal demo to reproduce this issue? https://runkit.com/ would be handy for this

@possibilities Love this lib and would love to pick it up :D 
PS: What‘s your concern for the 'negative side effect'?

**Comment by johhansantana** [comment]
@amio there's nothing complicated to replicate it.

```javascript
import { json, send } from "micro";
import { get, post, router } from "microrouter";
import * as cors from "micro-cors";

const index = (req, res) => send(res, 200, "hello");

const handler = (req, res) => router(get("/", index));

export default cors(handler);
```

go to `http://localhost:3000` and you get the error

**Comment by amio** [comment]
That would be more clear now. Thanks @johhansantana 

I use `micro-cors` with `microrouter` too, didn't encounter anything unexpected, so I was guessing if something related to this issue with `import routes from './routes'` from original example.

**Comment by amio** [comment]
@possibilities for your example, I think you might use `router(get("/", index))` instead of `(req, res) => router(get("/", index))` as the `handler`:
```
const micro = require('micro')
const { get, post, router } = require('microrouter')
const cors = require('micro-cors')

const index = async (req, res) => micro.send(res, 200, "hello")

const handler = router(get("/", index))

module.exports = cors()(handler)
```

**Comment by nottinhill** [comment]
Can you guys provide an example with multiple routes?

**Comment by amio** [comment]
@nottinhill Did you mean the usage of [microrouter](https://github.com/pedronauck/micro-router)?

**Comment by riddla** [comment]
@amio, as I am hitting the same error: did you mean to write `cors()(handler)` instead of `cors(handler);`?

**Comment by amio** [comment]
Yes, if you directly `const cors = require('micro-cors')`, then you should initialize it first `cors()(handler)`

**Comment by riddla** [comment]
Thanks @amio. That did the trick for me. 
@johhansantana, does the initialisation mentioned by @amio solve your problem, too?

**Comment by johhansantana** [comment]
I'm sorry @riddla I haven't worked with the library in a while. I will probably post an answer here when I try again.

**Comment by tim-phillips** [comment]
I use `microrouter` and `micro-cors` in my apis, here's how I do it:

```js
const cors = require('micro-cors')()
const { router, get, post } = require('microrouter')

const { getItems, getItem, createItem } = require('./handlers')

module.exports = cors(router(
  get('/', getItems)
  get('/:id', getItem),
  post('/', createItem)
))
```
