### ISSUE TITLE
Not on npm?

### ISSUE THREAD

**Issue by rauchg** [possibilities/micro-cors#30]
Thanks for this module <3 Found the missing `PATCH` method bug on 0.0.4. It's fixed in master. npm publish recommended 👍

**Comment by gabrielizaias** [comment]
I was about to ask for the same thing. 

@possibilities any plans to cut a new version soon?

Thanks for the handy module btw 🍻

**Comment by possibilities** [comment]
Oh shoot, published as 0.1.0 and will try to keep a better eye on this. Thanks!
