### ISSUE TITLE
Update npm module

### ISSUE THREAD

**Issue by pinguxx** [possibilities/micro-cors#40]
Can you please update the code in npm, cors is eating the extra arguments in the current version but the one in github seems to be handling it correctly

Thanks

**Comment by wmhilton** [comment]
Would love to see #42 get merged and `npm publish`ed 😁

**Comment by tim-phillips** [comment]
Sorry for the delay! I've merged #42 and am working on publishing to npm.

**Comment by tim-phillips** [comment]
Published!

Please try it out and let me know if there are any issues with the build on npm.
