### ISSUE TITLE
Process asterisks and commas in origin for really usable cors origin handling

### ISSUE THREAD

**Issue by huksley** [possibilities/micro-cors#47]
Using simple glob patterns

- If origin = * do nothing
- If origin matches https://*.domain.com evaluate and resolve origin on every request using Referer header
- If origin contains command, treat it as list of URIs, evaluate every item in list
- If no origin match, deny request with 400 Bad Request

**Comment by tim-phillips** [comment]
This has been discussed and rejected in #8 and #9. However, I'm all for it at this point. It seems to be an accepted practice. 

> The Cross-Origin Resource Sharing standard works by adding new HTTP headers that allow servers to describe the __set of origins__ that are permitted to read that information using a web browser.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Functional_overview

> Limiting the possible Access-Control-Allow-Origin values to a __set of allowed origins__ requires code on the server side to check the value of the Origin request header, compare that to a list of allowed origins, and then if the Origin value is in the list, to set the Access-Control-Allow-Origin value to the same value as the Origin value.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#Examples

> Sounds like the recommended way to do it is to have your server read the Origin header from the client, compare that to the list of domains you'd like to allow, and if it matches, echo the value of the Origin header back to the client as the Access-Control-Allow-Origin header in the response.

https://stackoverflow.com/a/1850482

Apologies for the delay in answering this, but we're making some changes with a v1 release and I think this is appropriate for that. This shouldn't create any breaking changes though.

**Comment by tim-phillips** [comment]
When the user includes an array of origins, we'll need to set the `Vary` header to let CDNs know that this headers varies per response and not to cache it.

> If the server specifies a single origin rather than the "*" wildcard, then the server should also include Origin in the Vary response header — to indicate to clients that server responses will differ based on the value of the Origin request header.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Access-Control-Allow-Origin

> Resources that wish to enable themselves to be shared with multiple Origins but do not respond uniformly with "*" must in practice generate the Access-Control-Allow-Origin header dynamically in response to every request they wish to allow. As a consequence, authors of such resources should send a Vary: Origin HTTP header or provide other appropriate control directives to prevent caching of such responses, which may be inaccurate if re-used across-origins.

https://www.w3.org/TR/cors/#resource-implementation

**Comment by tim-phillips** [comment]
We have a `v1` branch now and this will go in it. PR is welcome if you're able.

**Comment by lucasfischer** [comment]
wouldn't it be much more helpful if it would support origin options similar to this: https://github.com/expressjs/cors#configuration-options

if yes, i would like to work on this.

**Comment by tim-phillips** [comment]
Closed by #53
