### ISSUE TITLE
Publish beta pre-release

### ISSUE THREAD

**Issue by oklas** [possibilities/micro-cors#57]
Hi. Thank you for your work

I am interesting about publishing beta v1 pre-release

Current version does not allows to works without correct implementation of pre flight.
Pre flight implemented in #48 but did not published.

Currently I made a fork where built the lib and pushed it as a commit. That is added
as dependency to application. This way in not nice. Let me know any more good
way to install pre release v1 micro-cors library.

Thanks

**Comment by tim-phillips** [comment]
v1 is already available on npm as `micro-cors@next`

https://www.npmjs.com/package/micro-cors

**Comment by oklas** [comment]
Excelent, it was needed to be checked there, I suppose it is visible here at releses tab. Thank you!
