### ISSUE TITLE
Allow using multiple allowed origin domains

### ISSUE THREAD

**Issue by juanramb** [possibilities/micro-cors#8]
How can I use multiple allowed origins? 
Like https://github.com/expressjs/cors does...

**Comment by possibilities** [comment]
In CORS headers the origin is expressed as a string. This helper accepts an [`origin` option](https://github.com/possibilities/micro-cors#origin), e.g.:

```
const microCors = require('micro-cors')
const cors = microCors({ origin: 'sketchy-site.com' })
const handler = (req, res) => send(res, 200, 'ok!')

module.exports = cors(handler)
```

https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by jesseditson** [comment]
I believe what `express/cors` (and other techniques) are doing is to check if the origin is within a list of origins at runtime. So while the origin string itself is a single domain, the header is added dynamically. I'll spin up a PR, 1 sec
